"""add analytics indexes

Revision ID: 0c990e003fed
Revises: be6a52a7d5bb
Create Date: 2026-07-24 18:24:31.226523

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "0c990e003fed"
down_revision: Union[str, Sequence[str], None] = "be6a52a7d5bb"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index("ix_detection_jobs_created_at", "detection_jobs", ["created_at"], unique=False)
    op.create_index(
        "ix_detection_jobs_source_created_at",
        "detection_jobs",
        ["source_type", "created_at"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_detection_jobs_source_created_at", table_name="detection_jobs")
    op.drop_index("ix_detection_jobs_created_at", table_name="detection_jobs")
    # ### end Alembic commands ###
