"""create detection tables

Revision ID: be6a52a7d5bb
Revises:
Create Date: 2026-07-24 00:17:43.213639

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "be6a52a7d5bb"
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "detection_jobs",
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("public_id", sa.String(length=36), nullable=False),
        sa.Column(
            "source_type",
            sa.Enum(
                "image",
                "video",
                "camera",
                name="detection_source_type",
                native_enum=False,
                create_constraint=True,
            ),
            nullable=False,
        ),
        sa.Column(
            "status",
            sa.Enum(
                "pending",
                "processing",
                "completed",
                "failed",
                name="detection_job_status",
                native_enum=False,
                create_constraint=True,
            ),
            server_default="pending",
            nullable=False,
        ),
        sa.Column("original_filename", sa.String(length=255), nullable=False),
        sa.Column("stored_filename", sa.String(length=255), nullable=False),
        sa.Column("result_filename", sa.String(length=255), nullable=True),
        sa.Column("mime_type", sa.String(length=100), nullable=False),
        sa.Column("file_size_bytes", sa.BigInteger(), nullable=False),
        sa.Column("model_name", sa.String(length=100), nullable=False),
        sa.Column("device", sa.String(length=32), nullable=False),
        sa.Column(
            "confidence_threshold",
            sa.Numeric(precision=5, scale=4),
            server_default=sa.text("0.2500"),
            nullable=False,
        ),
        sa.Column("total_frames", sa.Integer(), nullable=True),
        sa.Column("processed_frames", sa.Integer(), nullable=True),
        sa.Column("detected_object_count", sa.Integer(), server_default="0", nullable=False),
        sa.Column("duration_ms", sa.Integer(), nullable=True),
        sa.Column("completed_at", sa.DateTime(), nullable=True),
        sa.Column("error_message", sa.Text(), nullable=True),
        sa.Column(
            "created_at", sa.DateTime(), server_default=sa.text("CURRENT_TIMESTAMP"), nullable=False
        ),
        sa.Column(
            "updated_at", sa.DateTime(), server_default=sa.text("CURRENT_TIMESTAMP"), nullable=False
        ),
        sa.CheckConstraint(
            "confidence_threshold >= 0 AND confidence_threshold <= 1",
            name=op.f("ck_detection_jobs_confidence_threshold_range"),
        ),
        sa.CheckConstraint(
            "detected_object_count >= 0",
            name=op.f("ck_detection_jobs_detected_object_count_non_negative"),
        ),
        sa.CheckConstraint(
            "file_size_bytes >= 0", name=op.f("ck_detection_jobs_file_size_non_negative")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_detection_jobs")),
        sa.UniqueConstraint("stored_filename", name=op.f("uq_detection_jobs_stored_filename")),
    )
    op.create_index(
        op.f("ix_detection_jobs_public_id"), "detection_jobs", ["public_id"], unique=True
    )
    op.create_index(
        "ix_detection_jobs_status_created_at",
        "detection_jobs",
        ["status", "created_at"],
        unique=False,
    )
    op.create_table(
        "detection_objects",
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("job_id", sa.BigInteger(), nullable=False),
        sa.Column("frame_index", sa.Integer(), nullable=False),
        sa.Column("track_id", sa.BigInteger(), nullable=True),
        sa.Column("class_id", sa.SmallInteger(), nullable=False),
        sa.Column("class_name", sa.String(length=64), nullable=False),
        sa.Column("confidence", sa.Numeric(precision=6, scale=5), nullable=False),
        sa.Column("x1", sa.Float(), nullable=False),
        sa.Column("y1", sa.Float(), nullable=False),
        sa.Column("x2", sa.Float(), nullable=False),
        sa.Column("y2", sa.Float(), nullable=False),
        sa.Column(
            "created_at", sa.DateTime(), server_default=sa.text("CURRENT_TIMESTAMP"), nullable=False
        ),
        sa.Column(
            "updated_at", sa.DateTime(), server_default=sa.text("CURRENT_TIMESTAMP"), nullable=False
        ),
        sa.CheckConstraint(
            "confidence >= 0 AND confidence <= 1",
            name=op.f("ck_detection_objects_confidence_range"),
        ),
        sa.CheckConstraint(
            "x1 >= 0 AND y1 >= 0 AND x2 >= x1 AND y2 >= y1",
            name=op.f("ck_detection_objects_bounding_box_coordinates"),
        ),
        sa.ForeignKeyConstraint(
            ["job_id"],
            ["detection_jobs.id"],
            name=op.f("fk_detection_objects_job_id_detection_jobs"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_detection_objects")),
    )
    op.create_index(
        "ix_detection_objects_job_id",
        "detection_objects",
        ["job_id"],
        unique=False,
    )
    op.create_index(
        "ix_detection_objects_job_class",
        "detection_objects",
        ["job_id", "class_name"],
        unique=False,
    )
    op.create_index(
        "ix_detection_objects_job_frame",
        "detection_objects",
        ["job_id", "frame_index"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    op.drop_table("detection_objects")
    op.drop_table("detection_jobs")
