"""add video processing fields

Revision ID: da654220822b
Revises: 0c990e003fed
Create Date: 2026-07-25 01:00:14.928510

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'da654220822b'
down_revision: Union[str, Sequence[str], None] = '0c990e003fed'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('detection_jobs', sa.Column('celery_task_id', sa.String(length=50), nullable=True))
    op.add_column('detection_jobs', sa.Column('progress_percent', sa.SmallInteger(), server_default='0', nullable=False))
    op.add_column('detection_jobs', sa.Column('unique_object_count', sa.Integer(), server_default='0', nullable=False))
    op.add_column('detection_jobs', sa.Column('video_duration_ms', sa.BigInteger(), nullable=True))
    op.create_unique_constraint(op.f('uq_detection_jobs_celery_task_id'), 'detection_jobs', ['celery_task_id'])
    # ### end Alembic commands ###
    op.execute(
        """
        UPDATE detection_jobs
        SET
            progress_percent = 100,
            unique_object_count = detected_object_count
        WHERE
            source_type = 'image'
            AND status = 'completed'
        """
    )


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('uq_detection_jobs_celery_task_id'), 'detection_jobs', type_='unique')
    op.drop_column('detection_jobs', 'video_duration_ms')
    op.drop_column('detection_jobs', 'unique_object_count')
    op.drop_column('detection_jobs', 'progress_percent')
    op.drop_column('detection_jobs', 'celery_task_id')
    # ### end Alembic commands ###
